name: Build and Test (non-main)

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r x-delete-posts/requirements.txt
          pip install build twine pylint

      - name: Test application setup (import main modules)
        run: |
          PYTHONPATH=x-delete-posts python -c "import xcleaner.main; import xcleaner.delete_all_x_posts; import xcleaner.authenticate_x"
        shell: bash

      - name: Run pylint
        run: |
          pylint x-delete-posts/xcleaner

      - name: Run unit tests
        run: |
          cd x-delete-posts
          python -m pytest tests -v

      - name: Clean dist directory
        run: |
          cd x-delete-posts
          python -c "import shutil, os; d='dist'; shutil.rmtree(d) if os.path.exists(d) else None"

      - name: Build package
        run: |
          cd x-delete-posts
          python -m build

      - name: Upload dist artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: x-delete-posts/dist/*
